micro_movie/微电影/app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,FileField,TextAreaField,SelectField
from wtforms.validators import DataRequired, ValidationError,Email,Regexp,EqualTo

class RegistForm(FlaskForm):
    name=StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "昵称",

            # 必填
            "required": "required",

        }
    )



    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入昵称！'),
            Email('邮箱格式不正确')
        ],
        description='昵称',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "邮箱",
            # 必填
            "required": "required",

        }
    )

    phone=StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号'),
            Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$",message='手机格式不正确'),
        ],
        description='手机',
        render_kw={
            'class':'form-control input-lg',
            "placeholder": "手机",
        }
    )

    pwd=PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码'),
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "密码",
        }
    )

    repwd = PasswordField(
        label='确认密码',
        validators=[
            DataRequired('请再输入一次密码'),
            EqualTo('pwd','两次密码不一致'),


        ],
        description='确认密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "确认密码",
        }
    )
    submit=SubmitField(
        label='注册',
        render_kw={
            'class':'btn btn-lg btn-success btn-block',
        }
    )

class LoginForm(FlaskForm):
    name=StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号！')
        ],
        description='用户名/邮箱/手机号码',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "用户名/邮箱/手机号码",

            # 必填
            "required": "required",

        }
    )
    pwd=PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码'),

        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "密码",
        }
    )

    submit = SubmitField(
        label='登录',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block',
        }
    )

class UserForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={

            "class": "form-control",
            "placeholder": "昵称",

            # 必填
            "required": "required",

        }
    )

    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入昵称！'),
            Email('邮箱格式不正确')
        ],
        description='昵称',
        render_kw={

            "class": "form-control",
            "placeholder": "邮箱",
            # 必填
            "required": "required",

        }
    )

    face = FileField(
        label="头像",
        validators=[

        ],
        description="头像",
    )

    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号'),
            Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$", message='手机格式不正确'),
        ],
        description='手机',
        render_kw={
            'class': 'form-control',
            "placeholder": "手机",
        }
    )

    info = TextAreaField(
        label='简介',
        validators=[

        ],
        description='简介',
        render_kw={
            'class': "form-control",
            'rows': "10",



        },
    )

    submit = SubmitField(
        label='提交',
        render_kw={

            "class": "btn btn-primary"
        }

    )



class Pwdform(FlaskForm):
    pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码'),
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "请输入旧密码！",
        }
    )

    newpwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码'),
        ],
        description='新密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "请输入新密码！",
        }
    )

    repwd = PasswordField(
        label='重复新密码',
        validators=[
            DataRequired('请再输入新密码'),
            EqualTo('newpwd', '两次密码不一致'),

        ],
        description='确认密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "确认密码",
        }
    )
    submit = SubmitField(
        label='修改',
        render_kw={
            "class": "btn btn-primary"
        }

    )

class CommentForm(FlaskForm):

    content = TextAreaField(
        label='评论',
        validators=[
             DataRequired('请输入评论'),
        ],
        description='评论',
        render_kw={
            'rows': "10",
            'id':'input_content',
        },
    )


    submit = SubmitField(
        label='提交评论',
        render_kw={
            "class": "btn btn-success",
            "id" : "btn-sub"
        }

    )

micro_movie/微电影/app/home/__init__.py
from flask import Blueprint

home=Blueprint("home", __name__)

import app.home.views

micro_movie/微电影/app/home/views.py
import json
import os
import uuid

from flask_wtf import csrf
from werkzeug.utils import secure_filename

from . import home
from flask import render_template,redirect,url_for,flash,session,request
from app.home.forms import RegistForm,LoginForm,UserForm,Pwdform,CommentForm
from app.models import User,Userlog,Tag,Movie,Comment,Movicecol
from werkzeug.security import generate_password_hash
from app import db,app
from datetime import datetime
from functools import wraps


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime("%Y%m%d%H&M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


def home_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "username" not in session:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function



@home.route("/login/",methods=['POST',"GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if user ==None :
            flash("密码或账号错误",'err')
            return redirect(url_for("home.login"))
        if not user.check_pwd(data['pwd']):
            flash('密码或账号错误','err')
            return redirect(url_for("home.login"))
        if user.status==0:
            flash('账号被冻结','err')
        session['username'] = data['name']
        session['user_id']=user.id
        userlog=Userlog(
            user_id=user.id,
            # 获取ip
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(request.args.get('next') or url_for('home.index',page=1))

    username = get_username()
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/login.html",form=form,context=context)


@home.route("/logout/")
def logout():
    session.pop('username', None)
    return redirect(url_for("home.login"))


@home.route("/regist/",methods=["POST",'GET'])
def regist():
    form=RegistForm()

    if form.validate_on_submit():
        data=form.data

        user_count=User.query.filter_by(name=data['name']).count()
        if user_count==1:
            flash('该用户已重复','err')

            return redirect(url_for('home.regist'))

        user = User(
            name=data['name'],
            pwd=generate_password_hash(data['pwd']),
            email=data['email'],
            phone=data['phone'],
            uuid=uuid.uuid4().hex,

        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("home.login"))
    username = get_username()
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/regist.html",form=form,context=context)


#会员中心
@home.route("/user/",methods=['GET','POST'])
@home_login_req
def user():
    username = get_username()
    form=UserForm()
    user=User.query.get_or_404(int(session['user_id']))
    if request.method=="GET":
        form.name.data=user.name
        form.email.data=user.email
        form.info.data=user.info
        form.face.data=user.face
        form.phone.data=user.phone

    if form.validate_on_submit():
        data=form.data
        if not os.path.exists(app.config['UPUSER_DIR']):
            os.makedirs(app.config["UPUSER_DIR"])
            os.chmod(app.config["UPUSER_DIR"],os.O_RDWR)

        if form.face.data.filename != None:
            file_url = secure_filename(form.face.data.filename)
            url = change_filename(file_url)
            form.face.data.save(app.config["UPUSER_DIR"] + url)

        name_count=User.query.filter_by(name=data['name']).count()
        if name_count==1 and user.name != data['name']:
            flash('昵称重复','err')
            return redirect(url_for('home.user'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if phone_count == 1 and user.phone != data['phone']:
            flash('手机号重复', 'err')
            return redirect(url_for('home.user'))

        email_count = User.query.filter_by(email=data['email']).count()
        if email_count == 1 and user.email != data['email']:
            flash('邮箱重复', 'err')
            return redirect(url_for('home.user'))

        user.name=data['name']
        user.phone=data['phone']
        user.face = url
        user.email=data['email']
        user.info=data['info']
        db.session.add(user)
        db.session.commit()
        flash('修改成功','ok')
        return redirect(url_for('home.user'))

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/user.html",context=context,form=form,user=user)

# 修改密码
@home.route("/pwd/",methods=['POST',"GET"])
@home_login_req
def pwd():
    username=get_username()
    form=Pwdform()
    user = User.query.get_or_404(int(session['user_id']))
    if form.validate_on_submit():
        data = form.data

        if not user.check_pwd(data['pwd']):
            flash('旧密码错误', 'err')
            return redirect(url_for("home.pwd"))

        user.pwd = generate_password_hash(data['newpwd'])
        db.session.add(user)
        db.session.commit()
        flash('修改成功', 'ok')
        return redirect(url_for('home.pwd'))
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/pwd.html",context=context,form=form)

#评论
@home.route("/comment/<int:page>")
@home_login_req
def comment(page=1):
    username = get_username()

    page_data = Comment.query.filter_by(
        user_id=int(session['user_id'])
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/comments.html",context=context,user=user,page=page_data)

#登陆日志
@home.route("/loginlog/<int:page>")
@home_login_req
def loginlog(page):
    username = get_username()
    if page == None:
        page = 1

    page_data = Userlog.query.filter_by(
            user_id=int(session['user_id'])
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/loginlog.html",context=context,page=page_data)

#电影收藏
@home.route("/moviecol_add/",methods=['GET'])
@home_login_req
def moviecol_add():
    username = get_username()
    uid=request.args.get('uid','')
    mid=request.args.get('mid','')
    moviecol=Movicecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid),
    ).count()
    if moviecol==1:
        data=dict(ok=0)
    else:
        moviecol=Movicecol(
            user_id=int(uid),
            movie_id=int(mid),

        )
        db.session.add(moviecol)
        db.session.commit()
        data=dict(ok=1)
    return json.dumps(data)

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/user/moviecol.html",context=context)

#电影收藏
@home.route("/moviecol/<int:page>",methods=['GET'])
@home_login_req
def moviecol(page=1):
    username = get_username()


    page_data = Movicecol.query.filter_by(
        user_id=int(session['user_id'])
    ).order_by(
        Movicecol.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目


    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/user/moviecol.html",context=context,page=page_data)


# 主页
@home.route("/<int:page>/")
def index(page=1):

    tags=Tag.query.all()

    page_data=Movie.query


    tid=request.args.get('tid',0)
    if int(tid)!=0:
        page_data=page_data.filter_by(tag_id=int(tid))

    star=request.args.get('star',0)
    if int(star)!=0:
        page_data=page_data.filter_by(star=int(star))

    time=request.args.get('time',0)
    if int(time)!=0:
        if int(time) ==1:
            page_data=page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )

    # 播放数量
    pm=request.args.get('pm',0)
    if int(pm)!=0:
        if int(pm) ==1:
            page_data=page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论数量
    cm=request.args.get('cm',0)
    if int(cm) !=0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.comment.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.comment.asc()
            )

    page_data=page_data.paginate(page=page,per_page=10)

    # 构建一个参数字典
    p=dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm,
    )

    username=get_username()


    if username != None:
        context={
           'login':username
        }
    else:
        context={
            'login':" "
        }
    return render_template("home/index.html",context=context,tags=tags,p=p,page=page_data)

#动画
@home.route("/animation/")
def animation():

micro_movie/微电影/app/templates/home/user/comments.html
{% extends "home/base.html" %}
{% import "ui/admin_page.html" as pg %}
{% block body %}
    <div class="container" style="margin-top:76px">
        <div class="col-md-3">
            <div class="list-group">
                <a href="{{ url_for("home.user") }}" class="list-group-item">
                    <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
                </a>
                <a href="{{ url_for("home.pwd") }}" class="list-group-item">
                    <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
                </a>
                <a href="{{ url_for("home.comment",page=1) }}" class="list-group-item active">
                    <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
                </a>
                <a href="{{ url_for("home.loginlog",page=1) }}" class="list-group-item">
                    <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
                </a>
                <a href="{{ url_for("home.moviecol",page=1) }}" class="list-group-item">
                    <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
                </a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
                </div>
                <div class="panel-body">
                    <ul class="commentList">
                        {% for foo in page.items %}
                            <li class="item cl">
                                <a href="user.html">
                                    <i class="avatar size-L radius">
                                        <img alt="50x50" src="{{ url_for("static",filename='upload/user/'+foo.user.face) }}"
                                             class="img-circle"
                                             style="height:50px;width:50px;border:1px solid #abcdef;">
                                    </i>
                                </a>
                                <div class="comment-main">
                                    <header class="comment-header">
                                        <div class="comment-meta">
                                            <a class="comment-author" href="user.html">{{ foo.user.name }}</a>
                                            评论于
                                            <time title="2016-12-07 09:12:51"
                                                  datetime="2016-12-07 09:12:51">{{ foo.addtime }}</time>
                                        </div>
                                    </header>
                                    <div class="comment-body">
                                        <p>{{ foo.content  |safe }}</p>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}


                    </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-md-12 text-center">
        {{ pg.page(page,'home.comment') }}
    </div>

{% endblock %}

micro_movie/微电影/app/templates/home/user/loginlog.html
{% extends "home/base.html" %}
{% import "ui/admin_page.html" as pg %}
{% block body %}
 <div class="container" style="margin-top:76px">
    <div class="col-md-3">
        <div class="list-group">
            <a href="{{ url_for("home.user") }}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
            <a href="{{ url_for("home.pwd") }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a href="{{ url_for("home.comment",page=1) }}" class="list-group-item ">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a href="{{ url_for("home.loginlog",page=1) }}" class="list-group-item active">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a href="{{ url_for("home.moviecol",page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>
 <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;登录日志</h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <tr>
                        <td style="width:10%">编号</td>
                        <td style="width:30%">登录时间</td>
                        <td style="width:30%">登录IP</td>

                    </tr>
                    {% for v in page.items %}
                        <tr>
                            <td>{{ v.id }}</td>
                            <td>{{ v.addtime }}</td>
                            <td>{{ v.ip }}</td>
                        </tr>
                    {% endfor %}


                </table>
            </div>
         <div class="box-footer clearfix">
                        {{ pg.page(page,'home.loginlog') }}
                    </div>
        </div>
    </div>
</div>

{% endblock %}

micro_movie/微电影/app/templates/home/user/moviecol.html
{% extends "home/base.html" %}
{% import "ui/admin_page.html" as pg %}
{% block body %}
    <div class="container" style="margin-top:76px">
    <div class="col-md-3">
        <div class="list-group">
            <a href="{{ url_for("home.user") }}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
            <a href="{{ url_for("home.pwd") }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a href="{{ url_for("home.comment",page=1) }}" class="list-group-item ">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a href="{{ url_for("home.loginlog",page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a href="{{ url_for("home.moviecol",page=1) }}" class="list-group-item active">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
            </div>
            <div class="panel-body">
                {% for foo in page.items %}
                <div class="col-md-12">
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ url_for("home.play",page=1,id=foo.movie.id) }}">
                                <img class="media-object"  style="width: 131px;height: 83px" src="{{ url_for("static",filename="upload/"+foo.movie.logo) }}" alt="环太平洋">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{ foo.movie.title }}<a href="{{ url_for("home.play",id=foo.movie.id,page=1) }}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                            {{ foo.movie.info }}
                        </div>
                    </div>
                {% endfor %}


                <div class="col-md-12 text-center" style="margin-top:6px;">
                    {{ pg.page(page,'home.moviecol') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

micro_movie/微电影/app/templates/home/user/pwd.html
{% extends "home/base.html" %}
{% block body %}
    <div class="container" style="margin-top:76px">
        <div class="col-md-3">
            <div class="list-group">
                <a href="{{ url_for("home.user") }}" class="list-group-item">
                    <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
                </a>
                <a href="{{ url_for("home.pwd") }}" class="list-group-item active">
                    <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
                </a>
                <a href="{{ url_for("home.comment",page=1) }}" class="list-group-item ">
                    <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
                </a>
                <a href="{{ url_for("home.loginlog",page=1) }}" class="list-group-item">
                    <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
                </a>
                <a href="{{ url_for("home.moviecol",page=1) }}" class="list-group-item">
                    <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
                </a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;会员中心</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post">
                        {% for msg in get_flashed_messages(category_filter=['ok']) %}
                            <h4 style="color: #0f9e60">{{ msg }}</h4>
                        {% endfor %}
                        {% for msg in get_flashed_messages(category_filter=['err']) %}
                            <h4 style="color: red"> {{ msg }}</h4>
                        {% endfor %}
                        <fieldset>
                            <div class="form-group">
                                <label for="input_oldpwd"><span
                                        class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.pwd.label }}</label>
                                {{ form.pwd }}
                                {% for foo in form.pwd.errors %}
                                    <div class="col-md-12">
                                        <font style="color: red">{{ foo }}</font>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_oldpwd"></div>
                            <div class="form-group">
                                <label for="input_newpwd"><span
                                        class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.newpwd.label }}</label>
                                {{ form.newpwd }}
                                {% for foo in form.newpwd.errors %}
                                    <div class="col-md-12">
                                        <font style="color: red">{{ foo }}</font>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                <label for="input_newpwd"><span
                                        class="glyphicon glyphicon-lock"></span>{{ form.repwd.label }}</label>
                                {{ form.repwd }}
                                {% for foo in form.repwd.errors %}
                                    <div class="col-md-12">
                                        <font style="color: red">{{ foo }}</font>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_newpwd"></div>
                            {{ form.csrf_token }}
                            {{ form.submit }}
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>

{% endblock %}