micro_movie/微电影/app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,FileField,TextAreaField,SelectField
from wtforms.validators import DataRequired, ValidationError,Email,Regexp,EqualTo

class RegistForm(FlaskForm):
    name=StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "昵称",

            # 必填
            "required": "required",

        }
    )



    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入昵称！'),
            Email('邮箱格式不正确')
        ],
        description='昵称',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "邮箱",
            # 必填
            "required": "required",

        }
    )

    phone=StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号'),
            Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$",message='手机格式不正确'),
        ],
        description='手机',
        render_kw={
            'class':'form-control input-lg',
            "placeholder": "手机",
        }
    )

    pwd=PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码'),
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "密码",
        }
    )

    repwd = PasswordField(
        label='确认密码',
        validators=[
            DataRequired('请再输入一次密码'),
            EqualTo('pwd','两次密码不一致'),


        ],
        description='确认密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "确认密码",
        }
    )
    submit=SubmitField(
        label='注册',
        render_kw={
            'class':'btn btn-lg btn-success btn-block',
        }
    )

class LoginForm(FlaskForm):
    name=StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号！')
        ],
        description='用户名/邮箱/手机号码',
        render_kw={

            "class": "form-control input-lg",
            "placeholder": "用户名/邮箱/手机号码",

            # 必填
            "required": "required",

        }
    )
    pwd=PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码'),

        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            "placeholder": "密码",
        }
    )

    submit = SubmitField(
        label='登录',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block',
        }
    )

class UserForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称！')
        ],
        description='昵称',
        render_kw={

            "class": "form-control",
            "placeholder": "昵称",

            # 必填
            "required": "required",

        }
    )

    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入昵称！'),
            Email('邮箱格式不正确')
        ],
        description='昵称',
        render_kw={

            "class": "form-control",
            "placeholder": "邮箱",
            # 必填
            "required": "required",

        }
    )

    face = FileField(
        label="头像",
        validators=[

        ],
        description="头像",
    )

    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号'),
            Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$", message='手机格式不正确'),
        ],
        description='手机',
        render_kw={
            'class': 'form-control',
            "placeholder": "手机",
        }
    )

    info = TextAreaField(
        label='简介',
        validators=[

        ],
        description='简介',
        render_kw={
            'class': "form-control",
            'rows': "10",



        },
    )

    submit = SubmitField(
        label='提交',
        render_kw={

            "class": "btn btn-primary"
        }

    )



class Pwdform(FlaskForm):
    pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码'),
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "请输入旧密码！",
        }
    )

    newpwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码'),
        ],
        description='新密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "请输入新密码！",
        }
    )

    repwd = PasswordField(
        label='重复新密码',
        validators=[
            DataRequired('请再输入新密码'),
            EqualTo('newpwd', '两次密码不一致'),

        ],
        description='确认密码',
        render_kw={
            'class': 'form-control ',
            "placeholder": "确认密码",
        }
    )
    submit = SubmitField(
        label='修改',
        render_kw={
            "class": "btn btn-primary"
        }

    )

class CommentForm(FlaskForm):

    content = TextAreaField(
        label='评论',
        validators=[
             DataRequired('请输入评论'),
        ],
        description='评论',
        render_kw={
            'rows': "10",
            'id':'input_content',
        },
    )


    submit = SubmitField(
        label='提交评论',
        render_kw={
            "class": "btn btn-success",
            "id" : "btn-sub"
        }

    )

micro_movie/微电影/app/home/__init__.py
from flask import Blueprint

home=Blueprint("home", __name__)

import app.home.views

micro_movie/微电影/app/home/views.py
import json
import os
import uuid

from flask_wtf import csrf
from werkzeug.utils import secure_filename

from . import home
from flask import render_template,redirect,url_for,flash,session,request
from app.home.forms import RegistForm,LoginForm,UserForm,Pwdform,CommentForm
from app.models import User,Userlog,Tag,Movie,Comment,Movicecol
from werkzeug.security import generate_password_hash
from app import db,app
from datetime import datetime
from functools import wraps


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.now().strftime("%Y%m%d%H&M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


def home_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "username" not in session:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function



@home.route("/login/",methods=['POST',"GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if user ==None :
            flash("密码或账号错误",'err')
            return redirect(url_for("home.login"))
        if not user.check_pwd(data['pwd']):
            flash('密码或账号错误','err')
            return redirect(url_for("home.login"))
        if user.status==0:
            flash('账号被冻结','err')
        session['username'] = data['name']
        session['user_id']=user.id
        userlog=Userlog(
            user_id=user.id,
            # 获取ip
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(request.args.get('next') or url_for('home.index',page=1))

    username = get_username()
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/login.html",form=form,context=context)


@home.route("/logout/")
def logout():
    session.pop('username', None)
    return redirect(url_for("home.login"))


@home.route("/regist/",methods=["POST",'GET'])
def regist():
    form=RegistForm()

    if form.validate_on_submit():
        data=form.data

        user_count=User.query.filter_by(name=data['name']).count()
        if user_count==1:
            flash('该用户已重复','err')

            return redirect(url_for('home.regist'))

        user = User(
            name=data['name'],
            pwd=generate_password_hash(data['pwd']),
            email=data['email'],
            phone=data['phone'],
            uuid=uuid.uuid4().hex,

        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("home.login"))
    username = get_username()
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/regist.html",form=form,context=context)


#会员中心
@home.route("/user/",methods=['GET','POST'])
@home_login_req
def user():
    username = get_username()
    form=UserForm()
    user=User.query.get_or_404(int(session['user_id']))
    if request.method=="GET":
        form.name.data=user.name
        form.email.data=user.email
        form.info.data=user.info
        form.face.data=user.face
        form.phone.data=user.phone

    if form.validate_on_submit():
        data=form.data
        if not os.path.exists(app.config['UPUSER_DIR']):
            os.makedirs(app.config["UPUSER_DIR"])
            os.chmod(app.config["UPUSER_DIR"],os.O_RDWR)

        if form.face.data.filename != None:
            file_url = secure_filename(form.face.data.filename)
            url = change_filename(file_url)
            form.face.data.save(app.config["UPUSER_DIR"] + url)

        name_count=User.query.filter_by(name=data['name']).count()
        if name_count==1 and user.name != data['name']:
            flash('昵称重复','err')
            return redirect(url_for('home.user'))

        phone_count = User.query.filter_by(phone=data['phone']).count()
        if phone_count == 1 and user.phone != data['phone']:
            flash('手机号重复', 'err')
            return redirect(url_for('home.user'))

        email_count = User.query.filter_by(email=data['email']).count()
        if email_count == 1 and user.email != data['email']:
            flash('邮箱重复', 'err')
            return redirect(url_for('home.user'))

        user.name=data['name']
        user.phone=data['phone']
        user.face = url
        user.email=data['email']
        user.info=data['info']
        db.session.add(user)
        db.session.commit()
        flash('修改成功','ok')
        return redirect(url_for('home.user'))

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/user.html",context=context,form=form,user=user)

# 修改密码
@home.route("/pwd/",methods=['POST',"GET"])
@home_login_req
def pwd():
    username=get_username()
    form=Pwdform()
    user = User.query.get_or_404(int(session['user_id']))
    if form.validate_on_submit():
        data = form.data

        if not user.check_pwd(data['pwd']):
            flash('旧密码错误', 'err')
            return redirect(url_for("home.pwd"))

        user.pwd = generate_password_hash(data['newpwd'])
        db.session.add(user)
        db.session.commit()
        flash('修改成功', 'ok')
        return redirect(url_for('home.pwd'))
    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/pwd.html",context=context,form=form)

#评论
@home.route("/comment/<int:page>")
@home_login_req
def comment(page=1):
    username = get_username()

    page_data = Comment.query.filter_by(
        user_id=int(session['user_id'])
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/comments.html",context=context,user=user,page=page_data)

#登陆日志
@home.route("/loginlog/<int:page>")
@home_login_req
def loginlog(page):
    username = get_username()
    if page == None:
        page = 1

    page_data = Userlog.query.filter_by(
            user_id=int(session['user_id'])
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }
    return render_template("home/user/loginlog.html",context=context,page=page_data)

#电影收藏
@home.route("/moviecol_add/",methods=['GET'])
@home_login_req
def moviecol_add():
    username = get_username()
    uid=request.args.get('uid','')
    mid=request.args.get('mid','')
    moviecol=Movicecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid),
    ).count()
    if moviecol==1:
        data=dict(ok=0)
    else:
        moviecol=Movicecol(
            user_id=int(uid),
            movie_id=int(mid),

        )
        db.session.add(moviecol)
        db.session.commit()
        data=dict(ok=1)
    return json.dumps(data)

    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/user/moviecol.html",context=context)

#电影收藏
@home.route("/moviecol/<int:page>",methods=['GET'])
@home_login_req
def moviecol(page=1):
    username = get_username()


    page_data = Movicecol.query.filter_by(
        user_id=int(session['user_id'])
    ).order_by(
        Movicecol.addtime.desc()
    ).paginate(page=page, per_page=10)  # per_page:一页显示数目


    if username != None:
        context = {
            'login': username
        }
    else:
        context = {
            'login': " "
        }

    return render_template("home/user/moviecol.html",context=context,page=page_data)


# 主页
@home.route("/<int:page>/")
def index(page=1):

    tags=Tag.query.all()

    page_data=Movie.query


    tid=request.args.get('tid',0)
    if int(tid)!=0:
        page_data=page_data.filter_by(tag_id=int(tid))

    star=request.args.get('star',0)
    if int(star)!=0:
        page_data=page_data.filter_by(star=int(star))

    time=request.args.get('time',0)
    if int(time)!=0:
        if int(time) ==1:
            page_data=page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )

    # 播放数量
    pm=request.args.get('pm',0)
    if int(pm)!=0:
        if int(pm) ==1:
            page_data=page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论数量
    cm=request.args.get('cm',0)
    if int(cm) !=0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.comment.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.comment.asc()
            )

    page_data=page_data.paginate(page=page,per_page=10)

    # 构建一个参数字典
    p=dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm,
    )

    username=get_username()


    if username != None:
        context={
           'login':username
        }
    else:
        context={
            'login':" "
        }
    return render_template("home/index.html",context=context,tags=tags,p=p,page=page_data)

#动画
@home.route("/animation/")
def animation():

micro_movie/微电影/app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
<link rel="stylesheet" type="text/css" href="{{ url_for("static",filename='anim/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
				<li id="imgCard0">
					<a href=""><span style="opacity:0;"></span></a>
					<img src="{{ url_for('static',filename='anim/main_banner/big0020150102211033.jpg') }}" alt="">
					<p style="bottom:0">周杰伦粉丝版MV</p>
				</li>
				<li id="imgCard1">
					<a href=""><span style="opacity:0.4;"></span></a>
					<img src="{{ url_for('static',filename='anim/main_banner/big0120150101183428.jpg') }}" alt="">
					<p>乐侃有声节目第二期</p>
				</li>
				<li id="imgCard2">
					<a href=""><span style="opacity:0.4;" ></span></a>
					<img src="{{ url_for('static',filename='anim/main_banner/big0320150101183351.jpg') }}" alt="">
					<p>乐见大牌：”荣“耀之声，”维“我独尊</p>
				</li>
				<li id="imgCard3">
					<a href=""><span style="opacity:0.4;"></span></a>
					<img src="{{ url_for('static',filename='anim/main_banner/big0420150101224343.jpg') }}" alt="">
					<p>王力宏四年心血结晶</p>
				</li>
				<li id="imgCard4">
					<a href=""><span style="opacity:0.4;"></span></a>
					<img src="{{ url_for('static',filename='anim/main_banner/big0720150102210934.jpg') }}" alt="">
					<p>MV精选：《武媚》女神团美艳大比拼</p>
				</li>
			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static',filename='anim/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='anim/js/script.js') }}"></script>

</body>
</html>

micro_movie/微电影/app/templates/home/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    {% block css %}{% endblock %}
    <style>
        .navbar-brand > img {
            display: inline;
        }

    </style>
    <style>
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
    {% block head %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" id="key_movie" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_serach"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            {% if context.login == " " %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
                                class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for("home.login") }}"><span
                                class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for("home.regist") }}"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for("home.logout") }}"><span
                                class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for("home.user") }}"><span
                                class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="curlink" href="#"><span
                                class="glyphicon glyphicon-log-in"></span>你好：{{ context.login }}</a>
                    </li>

                    <li>
                        <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
                                class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                    </li>


                    <li>
                        <a class="curlink" href="{{ url_for("home.logout") }}"><span
                                class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for("home.user") }}"><span
                                class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                    </li>
                </ul>

            {% endif %}

        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
</div>
<!--内容-->
{% block body %}

{% endblock %}
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });

        $("#do_serach").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search',page=1) }}?key="+key
        });
    });


    {% block js %}{% endblock %}
</script>
</body>
</html>

micro_movie/微电影/app/templates/home/index.html
{% extends "home/layout.html" %}
{% import "ui/admin_page.html" as pg %}

{% block body %}
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                        src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for foo in tags %}
                                <a class="label label-info"
                                   href="{{ url_for("home.index",page=1) }}?tid={{ foo.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"><span
                                        class="glyphicon glyphicon-tag"></span>{{ foo.name }}</a>
                            {% endfor %}


                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for foo in range(1,6) %}
                                <a class="label label-warning"
                                   href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ foo }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}"><span
                                        class="glyphicon glyphicon-star"></span>&nbsp;{{ foo }}星</a>
                            {% endfor %}


                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a class="label label-default"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=0 &pm={{ p['pm'] }}&cm={{ p['cm'] }}"><span
                                    class="glyphicon glyphicon-time"></span>&nbsp;最近</a>
                            &nbsp;
                            &nbsp;
                            <a class="label label-default"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}"><span
                                    class="glyphicon glyphicon-time"></span>&nbsp;更早</a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a class="label label-success"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=0&cm={{ p['cm'] }}"><span
                                    class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                            &nbsp;
                            <a class="label label-danger"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a class="label label-success"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm="><span
                                    class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                            &nbsp;
                            <a class="label label-danger"
                               href="{{ url_for("home.index",page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1"><span
                                    class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                        </td>
                    </tr>
                </table>
            </div>


            <!--<img data-original="holder.js/262x166"
                     class="img-responsive lazy center-block" alt="">-->
            {% for foo in page.items %}
                <div class="col-md-3">
                <div class="movielist text-center">
                <img src="{{ url_for('static',filename='upload/'+foo.logo) }}" style="width: 262px;height: 161px" class="img-responsive center-block"
                     alt="">
                <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                    <span style="color:#999;font-style: italic;">{{ foo.title }}</span><br>
                    <div>
                        {% for foo in range(0,foo.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                        {% endfor %}

                        {% for foo in range(0,5-foo.star) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                        {% endfor %}
                    </div>
                </div>
                <a href="{{ url_for('home.play',id=foo.id,page=1) }}" class="btn btn-primary" target="_blank" role="button"><span
                        class="glyphicon glyphicon-play"></span>&nbsp;播放</a>

            </div>
            </div>
            {% endfor %}

            <div class="col-md-12 text-center">
                {{ pg.page(page,'home.index') }}
            </div>
        </div>
    </div>
</section>
<!--电影列表-->

{% endblock %}

micro_movie/微电影/app/templates/home/search.html
{% extends "home/base.html" %}
{% import "ui/admin_page.html" as pg %}
{% block body %}
    <div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;">
                <li>与"{{ key }}"有关的电影，共{{ count }}部</li>
            </ol>
        </div>
        <div class="col-md-12">
            {% for v in page.items %}
            <div class="media">
                <div class="media-left">
                    <a href="{{ url_for("home.play",id=v.id,page=1) }}">
                        <img class="media-object" style="width: 131px;height: 83px" src="{{ url_for('static',filename='upload/'+v.logo) }}" alt="{{ v.title }}">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ v.title }}<a href="{{ url_for('home.play',id=v.id,page=1) }}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                    {{ v.info }}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-12 text-center">
            {{ pg.page(page,'home.search') }}
        </div>
    </div>
</div>

{% endblock %}